

export const myClassOptions = [
    { id: "Academic", title: "Academic" },
    //{ id: "Adventure", title: "Adventure" },
    //{ id: "Best Practice", title: "Best Practice" },
    { id: "Comedy", title: "Comedy" },
    //{ id: "Drama", title: "Drama" },
    { id: "Fiction", title: "Fiction" },
    { id: "Human Interest", title: "Human Interest" },
    { id: "Non-Fiction", title: "Non-Fiction" },
    //{ id: "Pleasure", title: "Pleasure" },
    //{ id: "Romance", title: "Romance" },
    { id: "Scary", title: "Scary" },
    //{ id: "Thriller", title: "Thriller" },
    //{ id: "Mixed", title: "Mixed" },
    { id: "Other", title: "Other" },
    //{ id: "None", title: "None" },
  ];

export const subjectOptions = [  
//{ id: "Art",  title: "Art"},
//{ id: "Biology",  title: "Biology"},
//{ id: "Business",  title: "Business"},
//{ id: "Chemistry",  title: "Chemistry"},
{ id: "English",  title: "English"},
//{ id: "Foreign Language",  title: "Foreign Language"},
{ id: "History",  title: "History"},
{ id: "Language Arts",  title: "Language Arts"},
{ id: "Life Skills",  title: "Life Skills"},
{ id: "Literature",  title: "Literature"},
{ id: "Mathematics",  title: "Mathematics"},
//{ id: "Music",  title: "Music"},
//{ id: "Physics",  title: "Physics"},
{ id: "Reading",  title: "Reading"},
//{ id: "Science",  title: "Science"},
//{ id: "Social Studies",  title: "Social Studies"},
//{ id: "Travel",  title: "Travel"},
{ id: "Vocabulary",  title: "Vocabulary"},
//{ id: "Mixed",  title: "Mixed"},
{ id: "Other", title: "Other"},
];

export const ageRangeOptions = [
{ id: 1, title: "PreSchool"},
{ id: 2, title: "Children"},
{ id: 3, title: "PG13"},
{ id: 4, title: "PG17"},
//{ id: 5, title: "Adult"},
{ id: 6, title: "All Ages"},
];

export const difficultyLevelOptions = [
{ id: 1, title: "PreSchool"},
{ id: 2, title: "K-1"},
{ id: 3, title: "Grade 1"},
{ id: 4, title: "Grade2"},
{ id: 5, title: "Grade 3"},
{ id: 6, title: "Grade 4"},
{ id: 7, title: "Grade 5"},
//{ id: 8, title: "Grammar School"},
{ id: 9, title: "Grade 6"},
{ id: 10, title: "Grade 7"},
{ id: 11, title: "Grade 8"},
//{ id: 12, title: "Jr High School"},
{ id: 13, title: "Grade 9"},
//{ id: 14, title: "Grade 10"},
//{ id: 15, title: "Grade 11"},
//{ id: 16, title: "Grade 12"},
{ id: 17, title: "High School"},
//{ id: 18, title: "College"},
//{ id: 19, title: "Freshman"},
//{ id: 20, title: "Sophomore"},
//{ id: 21, title: "Freshman"},
//{ id: 22, title: "Junior"},
//{ id: 23, title: "Senior"},
//{ id: 24, title: "Graduate"},
//{ id: 25, title: "Masters"},
//{ id: 26, title: "Wizard"},
{ id: 27, title: "General"},
];

export const categoryOptions = [
{ id: "Auditory Discrimination", title: "Auditory Discrimination"},
{ id: "Basic Reading", title: "Basic Reading"},
//{ id: "Behavior", title: "Behavior"},
//{ id: "Communication", title: "Communication"},
{ id: "Comprehension", title: "Comprehension"},
{ id: "Decoding", title: "Decoding"},
{ id: "Fluency", title: "Fluency"},
{ id: "Oral Language", title: "Oral Language"},
{ id: "Phoenetic", title: "Phoenetic"},
{ id: "Reasoning", title: "Reasoning"},
//{ id: "Social Skills", title: "Social Skills"},
{ id: "Speech", title: "Speech"},
{ id: "Visual Memory", title: "Visual Memory"},
{ id: "Vocabulary Expansion", title: "Vocabulary Expansion"},
{ id: "Word Recognition", title: "Word Recognition"},
{ id: "General", title: "General"},
//{ id: "Mixed", title: "Mixed"},
]